name = "origreen-bilingual-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
routes = [
  { pattern = "origreen.com", zone_name = "origreen.com" },
  { pattern = "www.origreen.com", zone_name = "origreen.com" }
] 